org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Common
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21]

# Forge
forge_version=47.4.10
forge_version_range=[47,)
forge_loader_version_range=[47,)

# Fabric
fabric_loader_version=0.18.4
fabric_api_version=0.92.7+1.20.1
fabric_loom_version=1.7-SNAPSHOT

# Mod
mod_group_id=com.mysticsbiomes
mod_id=mysticsbiomes
mod_name=Mystic's Biomes
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/mystics-biomes
mod_github_url=https://github.com/jayhillx/MysticsBiomes
mod_issues_url=https://github.com/jayhillx/MysticsBiomes/issues
mod_license=All Rights Reserved
mod_version=4.1
mod_authors=Jay
mod_description=Explore a world full of color.

# Dependencies
terrablender_version=3.0.1.10

# Other
forge_jei_version=15.20.0.112