package com.mysticsbiomes.datagen;

import com.mysticsbiomes.core.registry.RegistryObject;
import com.mysticsbiomes.init.MysticBlocks;
import net.minecraft.world.level.block.Block;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.stream.Stream;

public class MysticBlockFamilies {
    private static final Map<RegistryObject<Block>, MysticBlockFamily> FAMILIES = new LinkedHashMap<>();

    public static final MysticBlockFamily STRAWBERRY_WOOD = familyBuilder(MysticBlocks.STRAWBERRY_PLANKS)
            .log(MysticBlocks.STRAWBERRY_LOG)
            .wood(MysticBlocks.STRAWBERRY_WOOD)
            .strippedLog(MysticBlocks.STRIPPED_STRAWBERRY_LOG)
            .strippedWood(MysticBlocks.STRIPPED_STRAWBERRY_WOOD)
            .planks(MysticBlocks.STRAWBERRY_PLANKS)
            .stairs(MysticBlocks.STRAWBERRY_STAIRS)
            .slab(MysticBlocks.STRAWBERRY_SLAB)
            .fence(MysticBlocks.STRAWBERRY_FENCE)
            .fenceGate(MysticBlocks.STRAWBERRY_FENCE_GATE)
            .button(MysticBlocks.STRAWBERRY_BUTTON)
            .pressurePlate(MysticBlocks.STRAWBERRY_PRESSURE_PLATE)
            .trapdoor(MysticBlocks.STRAWBERRY_TRAPDOOR)
            .door(MysticBlocks.STRAWBERRY_DOOR)
            .sign(MysticBlocks.STRAWBERRY_SIGN, MysticBlocks.STRAWBERRY_WALL_SIGN)
            .hangingSign(MysticBlocks.STRAWBERRY_HANGING_SIGN, MysticBlocks.STRAWBERRY_WALL_HANGING_SIGN)
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .build();
    public static final MysticBlockFamily BLACK_CHERRY_WOOD = familyBuilder(MysticBlocks.BLACK_CHERRY_PLANKS)
            .log(MysticBlocks.BLACK_CHERRY_LOG)
            .wood(MysticBlocks.BLACK_CHERRY_WOOD)
            .strippedLog(MysticBlocks.STRIPPED_BLACK_CHERRY_LOG)
            .strippedWood(MysticBlocks.STRIPPED_BLACK_CHERRY_WOOD)
            .planks(MysticBlocks.BLACK_CHERRY_PLANKS)
            .stairs(MysticBlocks.BLACK_CHERRY_STAIRS)
            .slab(MysticBlocks.BLACK_CHERRY_SLAB)
            .fence(MysticBlocks.BLACK_CHERRY_FENCE)
            .fenceGate(MysticBlocks.BLACK_CHERRY_FENCE_GATE)
            .button(MysticBlocks.BLACK_CHERRY_BUTTON)
            .pressurePlate(MysticBlocks.BLACK_CHERRY_PRESSURE_PLATE)
            .trapdoor(MysticBlocks.BLACK_CHERRY_TRAPDOOR)
            .door(MysticBlocks.BLACK_CHERRY_DOOR)
            .sign(MysticBlocks.BLACK_CHERRY_SIGN, MysticBlocks.BLACK_CHERRY_WALL_SIGN)
            .hangingSign(MysticBlocks.BLACK_CHERRY_HANGING_SIGN, MysticBlocks.BLACK_CHERRY_WALL_HANGING_SIGN)
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .build();
    public static final MysticBlockFamily LAVENDER_WOOD = familyBuilder(MysticBlocks.LAVENDER_PLANKS)
            .log(MysticBlocks.LAVENDER_LOG)
            .wood(MysticBlocks.LAVENDER_WOOD)
            .strippedLog(MysticBlocks.STRIPPED_LAVENDER_LOG)
            .strippedWood(MysticBlocks.STRIPPED_LAVENDER_WOOD)
            .planks(MysticBlocks.LAVENDER_PLANKS)
            .stairs(MysticBlocks.LAVENDER_STAIRS)
            .slab(MysticBlocks.LAVENDER_SLAB)
            .fence(MysticBlocks.LAVENDER_FENCE)
            .fenceGate(MysticBlocks.LAVENDER_FENCE_GATE)
            .button(MysticBlocks.LAVENDER_BUTTON)
            .pressurePlate(MysticBlocks.LAVENDER_PRESSURE_PLATE)
            .trapdoor(MysticBlocks.LAVENDER_TRAPDOOR)
            .door(MysticBlocks.LAVENDER_DOOR)
            .sign(MysticBlocks.LAVENDER_SIGN, MysticBlocks.LAVENDER_WALL_SIGN)
            .hangingSign(MysticBlocks.LAVENDER_HANGING_SIGN, MysticBlocks.LAVENDER_WALL_HANGING_SIGN)
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .build();
    public static final MysticBlockFamily VANILLA_WOOD = familyBuilder(MysticBlocks.VANILLA_PLANKS)
            .log(MysticBlocks.VANILLA_LOG)
            .wood(MysticBlocks.VANILLA_WOOD)
            .strippedLog(MysticBlocks.STRIPPED_VANILLA_LOG)
            .strippedWood(MysticBlocks.STRIPPED_VANILLA_WOOD)
            .planks(MysticBlocks.VANILLA_PLANKS)
            .stairs(MysticBlocks.VANILLA_STAIRS)
            .slab(MysticBlocks.VANILLA_SLAB)
            .fence(MysticBlocks.VANILLA_FENCE)
            .fenceGate(MysticBlocks.VANILLA_FENCE_GATE)
            .button(MysticBlocks.VANILLA_BUTTON)
            .pressurePlate(MysticBlocks.VANILLA_PRESSURE_PLATE)
            .trapdoor(MysticBlocks.VANILLA_TRAPDOOR)
            .door(MysticBlocks.VANILLA_DOOR)
            .sign(MysticBlocks.VANILLA_SIGN, MysticBlocks.VANILLA_WALL_SIGN)
            .hangingSign(MysticBlocks.VANILLA_HANGING_SIGN, MysticBlocks.VANILLA_WALL_HANGING_SIGN)
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .build();
    public static final MysticBlockFamily LUSH_SANDSTONE = familyBuilder(MysticBlocks.LUSH_SANDSTONE)
            .full(MysticBlocks.LUSH_SANDSTONE)
            .stairs(MysticBlocks.LUSH_SANDSTONE_STAIRS)
            .slab(MysticBlocks.LUSH_SANDSTONE_SLAB)
            .wall(MysticBlocks.LUSH_SANDSTONE_WALL)
            .chiseled(MysticBlocks.CHISELED_LUSH_SANDSTONE)
            .cut(MysticBlocks.CUT_LUSH_SANDSTONE)
            .build();
    public static final MysticBlockFamily CUT_LUSH_SANDSTONE = familyBuilder(MysticBlocks.CUT_LUSH_SANDSTONE)
            .slab(MysticBlocks.CUT_LUSH_SANDSTONE_SLAB)
            .build();
    public static final MysticBlockFamily SMOOTH_LUSH_SANDSTONE = familyBuilder(MysticBlocks.SMOOTH_LUSH_SANDSTONE)
            .full(MysticBlocks.SMOOTH_LUSH_SANDSTONE)
            .stairs(MysticBlocks.SMOOTH_LUSH_SANDSTONE_STAIRS)
            .slab(MysticBlocks.SMOOTH_LUSH_SANDSTONE_SLAB)
            .build();
    public static final MysticBlockFamily PEACH_WOOD = familyBuilder(MysticBlocks.PEACH_PLANKS)
            .log(MysticBlocks.PEACH_LOG)
            .wood(MysticBlocks.PEACH_WOOD)
            .strippedLog(MysticBlocks.STRIPPED_PEACH_LOG)
            .strippedWood(MysticBlocks.STRIPPED_PEACH_WOOD)
            .planks(MysticBlocks.PEACH_PLANKS)
            .stairs(MysticBlocks.PEACH_STAIRS)
            .slab(MysticBlocks.PEACH_SLAB)
            .fence(MysticBlocks.PEACH_FENCE)
            .fenceGate(MysticBlocks.PEACH_FENCE_GATE)
            .button(MysticBlocks.PEACH_BUTTON)
            .pressurePlate(MysticBlocks.PEACH_PRESSURE_PLATE)
            .trapdoor(MysticBlocks.PEACH_TRAPDOOR)
            .door(MysticBlocks.PEACH_DOOR)
            .sign(MysticBlocks.PEACH_SIGN, MysticBlocks.PEACH_WALL_SIGN)
            .hangingSign(MysticBlocks.PEACH_HANGING_SIGN, MysticBlocks.PEACH_WALL_HANGING_SIGN)
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .build();
    public static final MysticBlockFamily MAPLE_WOOD = familyBuilder(MysticBlocks.MAPLE_PLANKS)
            .log(MysticBlocks.MAPLE_LOG)
            .wood(MysticBlocks.MAPLE_WOOD)
            .secondaryLog(MysticBlocks.WHITE_MAPLE_LOG)
            .secondaryWood(MysticBlocks.WHITE_MAPLE_WOOD)
            .strippedLog(MysticBlocks.STRIPPED_MAPLE_LOG)
            .strippedWood(MysticBlocks.STRIPPED_MAPLE_WOOD)
            .planks(MysticBlocks.MAPLE_PLANKS)
            .stairs(MysticBlocks.MAPLE_STAIRS)
            .slab(MysticBlocks.MAPLE_SLAB)
            .fence(MysticBlocks.MAPLE_FENCE)
            .fenceGate(MysticBlocks.MAPLE_FENCE_GATE)
            .button(MysticBlocks.MAPLE_BUTTON)
            .pressurePlate(MysticBlocks.MAPLE_PRESSURE_PLATE)
            .trapdoor(MysticBlocks.MAPLE_TRAPDOOR)
            .door(MysticBlocks.MAPLE_DOOR)
            .sign(MysticBlocks.MAPLE_SIGN, MysticBlocks.MAPLE_WALL_SIGN)
            .hangingSign(MysticBlocks.MAPLE_HANGING_SIGN, MysticBlocks.MAPLE_WALL_HANGING_SIGN)
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .build();
    public static final MysticBlockFamily SPRING_WOOD = familyBuilder(MysticBlocks.SPRING_PLANKS)
            .log(MysticBlocks.SPRING_BAMBOO_BLOCK)
            .strippedLog(MysticBlocks.STRIPPED_SPRING_BAMBOO_BLOCK)
            .planks(MysticBlocks.SPRING_PLANKS)
            .stairs(MysticBlocks.SPRING_STAIRS)
            .slab(MysticBlocks.SPRING_SLAB)
            .fence(MysticBlocks.SPRING_FENCE)
            .fenceGate(MysticBlocks.SPRING_FENCE_GATE)
            .button(MysticBlocks.SPRING_BUTTON)
            .pressurePlate(MysticBlocks.SPRING_PRESSURE_PLATE)
            .trapdoor(MysticBlocks.SPRING_TRAPDOOR)
            .door(MysticBlocks.SPRING_DOOR)
            .sign(MysticBlocks.SPRING_SIGN, MysticBlocks.SPRING_WALL_SIGN)
            .hangingSign(MysticBlocks.SPRING_HANGING_SIGN, MysticBlocks.SPRING_WALL_HANGING_SIGN)
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .build();
    public static final MysticBlockFamily SPRING_MOSAIC = familyBuilder(MysticBlocks.SPRING_MOSAIC)
            .planks(MysticBlocks.SPRING_MOSAIC)
            .stairs(MysticBlocks.SPRING_MOSAIC_STAIRS)
            .slab(MysticBlocks.SPRING_MOSAIC_SLAB)
            .build();
    public static final MysticBlockFamily SEA_FOAM_WOOD = familyBuilder(MysticBlocks.SEA_FOAM_PLANKS)
            .log(MysticBlocks.SEA_FOAM_LOG)
            .wood(MysticBlocks.SEA_FOAM_WOOD)
            .strippedLog(MysticBlocks.STRIPPED_SEA_FOAM_LOG)
            .strippedWood(MysticBlocks.STRIPPED_SEA_FOAM_WOOD)
            .planks(MysticBlocks.SEA_FOAM_PLANKS)
            .stairs(MysticBlocks.SEA_FOAM_STAIRS)
            .slab(MysticBlocks.SEA_FOAM_SLAB)
            .fence(MysticBlocks.SEA_FOAM_FENCE)
            .fenceGate(MysticBlocks.SEA_FOAM_FENCE_GATE)
            .button(MysticBlocks.SEA_FOAM_BUTTON)
            .pressurePlate(MysticBlocks.SEA_FOAM_PRESSURE_PLATE)
            .trapdoor(MysticBlocks.SEA_FOAM_TRAPDOOR)
            .door(MysticBlocks.SEA_FOAM_DOOR)
            .sign(MysticBlocks.SEA_FOAM_SIGN, MysticBlocks.SEA_FOAM_WALL_SIGN)
            .hangingSign(MysticBlocks.SEA_FOAM_HANGING_SIGN, MysticBlocks.SEA_FOAM_WALL_HANGING_SIGN)
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .build();
    public static final MysticBlockFamily TROPICAL_WOOD = familyBuilder(MysticBlocks.TROPICAL_PLANKS)
            .log(MysticBlocks.TROPICAL_LOG)
            .wood(MysticBlocks.TROPICAL_WOOD)
            .strippedLog(MysticBlocks.STRIPPED_TROPICAL_LOG)
            .strippedWood(MysticBlocks.STRIPPED_TROPICAL_WOOD)
            .planks(MysticBlocks.TROPICAL_PLANKS)
            .stairs(MysticBlocks.TROPICAL_STAIRS)
            .slab(MysticBlocks.TROPICAL_SLAB)
            .fence(MysticBlocks.TROPICAL_FENCE)
            .fenceGate(MysticBlocks.TROPICAL_FENCE_GATE)
            .button(MysticBlocks.TROPICAL_BUTTON)
            .pressurePlate(MysticBlocks.TROPICAL_PRESSURE_PLATE)
            .trapdoor(MysticBlocks.TROPICAL_TRAPDOOR)
            .door(MysticBlocks.TROPICAL_DOOR)
            .sign(MysticBlocks.TROPICAL_SIGN, MysticBlocks.TROPICAL_WALL_SIGN)
            .hangingSign(MysticBlocks.TROPICAL_HANGING_SIGN, MysticBlocks.TROPICAL_WALL_HANGING_SIGN)
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .flammable()
            .build();

    private static MysticBlockFamily.Builder familyBuilder(RegistryObject<Block> block) {
        MysticBlockFamily.Builder builder = new MysticBlockFamily.Builder(block);
        FAMILIES.put(block, builder.build());
        return builder;
    }

    public static Stream<MysticBlockFamily> getAllFamilies() {
        return FAMILIES.values().stream();
    }

}