package com.mysticsbiomes.datagen;

import com.mysticsbiomes.init.MysticBlocks;
import net.minecraft.world.level.block.Block;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.stream.Stream;

public class MysticBlockFamilies {
    private static final Map<Block, MysticBlockFamily> FAMILIES = new LinkedHashMap<>();

    public static final MysticBlockFamily STRAWBERRY_WOOD = familyBuilder(MysticBlocks.STRAWBERRY_PLANKS.get())
            .log(MysticBlocks.STRAWBERRY_LOG.get(), MysticBlocks.STRIPPED_STRAWBERRY_LOG.get())
            .wood(MysticBlocks.STRAWBERRY_WOOD.get(), MysticBlocks.STRIPPED_STRAWBERRY_WOOD.get())
            .planks(MysticBlocks.STRAWBERRY_PLANKS.get())
            .stairs(MysticBlocks.STRAWBERRY_STAIRS.get())
            .slab(MysticBlocks.STRAWBERRY_SLAB.get())
            .fence(MysticBlocks.STRAWBERRY_FENCE.get())
            .fenceGate(MysticBlocks.STRAWBERRY_FENCE_GATE.get())
            .button(MysticBlocks.STRAWBERRY_BUTTON.get())
            .pressurePlate(MysticBlocks.STRAWBERRY_PRESSURE_PLATE.get())
            .trapdoor(MysticBlocks.STRAWBERRY_TRAPDOOR.get())
            .door(MysticBlocks.STRAWBERRY_DOOR.get())
            .sign(MysticBlocks.STRAWBERRY_SIGN.get(), MysticBlocks.STRAWBERRY_WALL_SIGN.get())
            .hangingSign(MysticBlocks.STRAWBERRY_HANGING_SIGN.get(), MysticBlocks.STRAWBERRY_WALL_HANGING_SIGN.get())
            .recipeGroupPrefix("wooden")
            .recipeUnlockedBy("has_planks")
            .getFamily();
    ///public static final MysticBlockFamily BLACK_CHERRY_WOOD = familyBuilder(MysticBlocks.BLACK_CHERRY_PLANKS.get())
    ///        .log(MysticBlocks.BLACK_CHERRY_LOG.get())
    ///        .wood(MysticBlocks.BLACK_CHERRY_WOOD.get())
    ///        .strippedLog(MysticBlocks.STRIPPED_BLACK_CHERRY_LOG.get())
    ///        .strippedWood(MysticBlocks.STRIPPED_BLACK_CHERRY_WOOD.get())
    ///        .planks(MysticBlocks.BLACK_CHERRY_PLANKS.get())
    ///        .stairs(MysticBlocks.BLACK_CHERRY_STAIRS.get())
    ///        .slab(MysticBlocks.BLACK_CHERRY_SLAB.get())
    ///        .fence(MysticBlocks.BLACK_CHERRY_FENCE.get())
    ///        .fenceGate(MysticBlocks.BLACK_CHERRY_FENCE_GATE.get())
    ///        .button(MysticBlocks.BLACK_CHERRY_BUTTON.get())
    ///        .pressurePlate(MysticBlocks.BLACK_CHERRY_PRESSURE_PLATE.get())
    ///        .trapdoor(MysticBlocks.BLACK_CHERRY_TRAPDOOR.get())
    ///        .door(MysticBlocks.BLACK_CHERRY_DOOR.get())
    ///        .sign(MysticBlocks.BLACK_CHERRY_SIGN.get(), MysticBlocks.BLACK_CHERRY_WALL_SIGN.get())
    ///        .hangingSign(MysticBlocks.BLACK_CHERRY_HANGING_SIGN.get(), MysticBlocks.BLACK_CHERRY_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .getFamily();
    ///public static final MysticBlockFamily LAVENDER_WOOD = familyBuilder(MysticBlocks.LAVENDER_PLANKS.get())
    ///        .log(MysticBlocks.LAVENDER_LOG.get())
    ///        .wood(MysticBlocks.LAVENDER_WOOD.get())
    ///        .strippedLog(MysticBlocks.STRIPPED_LAVENDER_LOG.get())
    ///        .strippedWood(MysticBlocks.STRIPPED_LAVENDER_WOOD.get())
    ///        .planks(MysticBlocks.LAVENDER_PLANKS.get())
    ///        .stairs(MysticBlocks.LAVENDER_STAIRS.get())
    ///        .slab(MysticBlocks.LAVENDER_SLAB.get())
    ///        .fence(MysticBlocks.LAVENDER_FENCE.get())
    ///        .fenceGate(MysticBlocks.LAVENDER_FENCE_GATE.get())
    ///        .button(MysticBlocks.LAVENDER_BUTTON.get())
    ///        .pressurePlate(MysticBlocks.LAVENDER_PRESSURE_PLATE.get())
    ///        .trapdoor(MysticBlocks.LAVENDER_TRAPDOOR.get())
    ///        .door(MysticBlocks.LAVENDER_DOOR.get())
    ///        .sign(MysticBlocks.LAVENDER_SIGN.get(), MysticBlocks.LAVENDER_WALL_SIGN.get())
    ///        .hangingSign(MysticBlocks.LAVENDER_HANGING_SIGN.get(), MysticBlocks.LAVENDER_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .getFamily();
    ///public static final MysticBlockFamily PEACH_WOOD = familyBuilder(MysticBlocks.PEACH_PLANKS.get())
    ///        .log(MysticBlocks.PEACH_LOG.get())
    ///        .wood(MysticBlocks.PEACH_WOOD.get())
    ///        .strippedLog(MysticBlocks.STRIPPED_PEACH_LOG.get())
    ///        .strippedWood(MysticBlocks.STRIPPED_PEACH_WOOD.get())
    ///        .planks(MysticBlocks.PEACH_PLANKS.get())
    ///        .stairs(MysticBlocks.PEACH_STAIRS.get())
    ///        .slab(MysticBlocks.PEACH_SLAB.get())
    ///        .fence(MysticBlocks.PEACH_FENCE.get())
    ///        .fenceGate(MysticBlocks.PEACH_FENCE_GATE.get())
    ///        .button(MysticBlocks.PEACH_BUTTON.get())
    ///        .pressurePlate(MysticBlocks.PEACH_PRESSURE_PLATE.get())
    ///        .trapdoor(MysticBlocks.PEACH_TRAPDOOR.get())
    ///        .door(MysticBlocks.PEACH_DOOR.get())
    ///        .sign(MysticBlocks.PEACH_SIGN.get(), MysticBlocks.PEACH_WALL_SIGN.get())
    ///        .hangingSign(MysticBlocks.PEACH_HANGING_SIGN.get(), MysticBlocks.PEACH_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .getFamily();
    ///public static final MysticBlockFamily MAPLE_WOOD = familyBuilder(MysticBlocks.MAPLE_PLANKS.get())
    ///        .log(MysticBlocks.MAPLE_LOG.get())
    ///        .wood(MysticBlocks.MAPLE_WOOD.get())
    ///        .strippedLog(MysticBlocks.STRIPPED_MAPLE_LOG.get())
    ///        .strippedWood(MysticBlocks.STRIPPED_MAPLE_WOOD.get())
    ///        .planks(MysticBlocks.MAPLE_PLANKS.get())
    ///        .stairs(MysticBlocks.MAPLE_STAIRS.get())
    ///        .slab(MysticBlocks.MAPLE_SLAB.get())
    ///        .fence(MysticBlocks.MAPLE_FENCE.get())
    ///        .fenceGate(MysticBlocks.MAPLE_FENCE_GATE.get())
    ///        .button(MysticBlocks.MAPLE_BUTTON.get())
    ///        .pressurePlate(MysticBlocks.MAPLE_PRESSURE_PLATE.get())
    ///        .trapdoor(MysticBlocks.MAPLE_TRAPDOOR.get())
    ///        .door(MysticBlocks.MAPLE_DOOR.get())
    ///        .sign(MysticBlocks.MAPLE_SIGN.get(), MysticBlocks.MAPLE_WALL_SIGN.get())
    ///        .hangingSign(MysticBlocks.MAPLE_HANGING_SIGN.get(), MysticBlocks.MAPLE_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .getFamily();
    ///public static final MysticBlockFamily SPRING_WOOD = familyBuilder(MysticBlocks.SPRING_PLANKS.get())
    ///        .log(MysticBlocks.SPRING_BAMBOO_BLOCK.get())
    ///        .strippedLog(MysticBlocks.STRIPPED_SPRING_BAMBOO_BLOCK.get())
    ///        .planks(MysticBlocks.SPRING_PLANKS.get())
    ///        .stairs(MysticBlocks.SPRING_STAIRS.get())
    ///        .slab(MysticBlocks.SPRING_SLAB.get())
    ///        .fence(MysticBlocks.SPRING_FENCE.get())
    ///        .fenceGate(MysticBlocks.SPRING_FENCE_GATE.get())
    ///        .button(MysticBlocks.SPRING_BUTTON.get())
    ///        .pressurePlate(MysticBlocks.SPRING_PRESSURE_PLATE.get())
    ///        .trapdoor(MysticBlocks.SPRING_TRAPDOOR.get())
    ///        .door(MysticBlocks.SPRING_DOOR.get())
    ///        .sign(MysticBlocks.SPRING_SIGN.get(), MysticBlocks.SPRING_WALL_SIGN.get())
    ///        .hangingSign(MysticBlocks.SPRING_HANGING_SIGN.get(), MysticBlocks.SPRING_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .getFamily();
    ///public static final MysticBlockFamily SPRING_MOSAIC = familyBuilder(MysticBlocks.SPRING_MOSAIC.get())
    ///        .planks(MysticBlocks.SPRING_MOSAIC.get())
    ///        .stairs(MysticBlocks.SPRING_MOSAIC_STAIRS.get())
    ///        .slab(MysticBlocks.SPRING_MOSAIC_SLAB.get())
    ///        .getFamily();
    ///public static final MysticBlockFamily SEA_FOAM_WOOD = familyBuilder(MysticBlocks.SEA_FOAM_PLANKS.get())
    ///        .log(MysticBlocks.SEA_FOAM_LOG.get())
    ///        .wood(MysticBlocks.SEA_FOAM_WOOD.get())
    ///        .strippedLog(MysticBlocks.STRIPPED_SEA_FOAM_LOG.get())
    ///        .strippedWood(MysticBlocks.STRIPPED_SEA_FOAM_WOOD.get())
    ///        .planks(MysticBlocks.SEA_FOAM_PLANKS.get())
    ///        .stairs(MysticBlocks.SEA_FOAM_STAIRS.get())
    ///        .slab(MysticBlocks.SEA_FOAM_SLAB.get())
    ///        .fence(MysticBlocks.SEA_FOAM_FENCE.get())
    ///        .fenceGate(MysticBlocks.SEA_FOAM_FENCE_GATE.get())
    ///        .button(MysticBlocks.SEA_FOAM_BUTTON.get())
    ///        .pressurePlate(MysticBlocks.SEA_FOAM_PRESSURE_PLATE.get())
    ///        .trapdoor(MysticBlocks.SEA_FOAM_TRAPDOOR.get())
    ///        .door(MysticBlocks.SEA_FOAM_DOOR.get())
    ///        .sign(MysticBlocks.SEA_FOAM_SIGN.get(), MysticBlocks.SEA_FOAM_WALL_SIGN.get())
    ///        .hangingSign(MysticBlocks.SEA_FOAM_HANGING_SIGN.get(), MysticBlocks.SEA_FOAM_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .getFamily();
    ///public static final MysticBlockFamily TROPICAL_WOOD = familyBuilder(MysticBlocks.TROPICAL_PLANKS.get())
    ///        .log(MysticBlocks.TROPICAL_LOG.get())
    ///        .wood(MysticBlocks.TROPICAL_WOOD.get())
    ///        .strippedLog(MysticBlocks.STRIPPED_TROPICAL_LOG.get())
    ///        .strippedWood(MysticBlocks.STRIPPED_TROPICAL_WOOD.get())
    ///        .planks(MysticBlocks.TROPICAL_PLANKS.get())
    ///        .stairs(MysticBlocks.TROPICAL_STAIRS.get())
    ///        .slab(MysticBlocks.TROPICAL_SLAB.get())
    ///        .fence(MysticBlocks.TROPICAL_FENCE.get())
    ///        .fenceGate(MysticBlocks.TROPICAL_FENCE_GATE.get())
    ///        .button(MysticBlocks.TROPICAL_BUTTON.get())
    ///        .pressurePlate(MysticBlocks.TROPICAL_PRESSURE_PLATE.get())
    ///        .trapdoor(MysticBlocks.TROPICAL_TRAPDOOR.get())
    ///        .door(MysticBlocks.TROPICAL_DOOR.get())
    ///        .sign(MysticBlocks.TROPICAL_SIGN.get(), MysticBlocks.TROPICAL_WALL_SIGN.get())
    ///        .hangingSign(MysticBlocks.TROPICAL_HANGING_SIGN.get(), MysticBlocks.TROPICAL_WALL_HANGING_SIGN.get())
    ///        .recipeGroupPrefix("wooden")
    ///        .recipeUnlockedBy("has_planks")
    ///        .getFamily();
   ///public static final MysticBlockFamily VANILLA_WOOD = familyBuilder(MysticBlocks.VANILLA_PLANKS.get())
   ///        .log(MysticBlocks.VANILLA_LOG.get())
   ///        .wood(MysticBlocks.VANILLA_WOOD.get())
   ///        .strippedLog(MysticBlocks.STRIPPED_VANILLA_LOG.get())
   ///        .strippedWood(MysticBlocks.STRIPPED_VANILLA_WOOD.get())
   ///        .planks(MysticBlocks.VANILLA_PLANKS.get())
   ///        .stairs(MysticBlocks.VANILLA_STAIRS.get())
   ///        .slab(MysticBlocks.VANILLA_SLAB.get())
   ///        .fence(MysticBlocks.VANILLA_FENCE.get())
   ///        .fenceGate(MysticBlocks.VANILLA_FENCE_GATE.get())
   ///        .button(MysticBlocks.VANILLA_BUTTON.get())
   ///        .pressurePlate(MysticBlocks.VANILLA_PRESSURE_PLATE.get())
   ///        .trapdoor(MysticBlocks.VANILLA_TRAPDOOR.get())
   ///        .door(MysticBlocks.VANILLA_DOOR.get())
   ///        .sign(MysticBlocks.VANILLA_SIGN.get(), MysticBlocks.VANILLA_WALL_SIGN.get())
   ///        .hangingSign(MysticBlocks.VANILLA_HANGING_SIGN.get(), MysticBlocks.VANILLA_WALL_HANGING_SIGN.get())
   ///        .recipeGroupPrefix("wooden")
   ///        .recipeUnlockedBy("has_planks")
   ///        .getFamily();

    private static MysticBlockFamily.Builder familyBuilder(Block block) {
        MysticBlockFamily.Builder builder = new MysticBlockFamily.Builder(block);
        FAMILIES.put(block, builder.getFamily());
        return builder;
    }

    public static Stream<MysticBlockFamily> getAllFamilies() {
        return FAMILIES.values().stream();
    }

}