modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

logoFile="logo.png"

[[mods]]
modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.mysticsbiomes]]
modId="terrablender"

mandatory=true

versionRange="[3.0.0,)"

ordering="AFTER"

side="BOTH"