package com.mysticsbiomes.init;

import com.mysticsbiomes.common.block.grower.MysticTreeGrowers;
import com.mysticsbiomes.common.block.state.MysticBlockSetTypes;
import com.mysticsbiomes.common.block.state.MysticWoodTypes;
import com.mysticsbiomes.core.registry.RegistryObject;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.worldgen.features.TreeFeatures;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.NoteBlockInstrument;
import net.minecraft.world.level.material.MapColor;

import java.util.function.Supplier;

import static com.mysticsbiomes.MysticsBiomes.REGISTRY;
import static com.mysticsbiomes.common.block.BlockTemplate.*;
import static com.mysticsbiomes.common.block.BlockTemplate.door;

public class MysticBlocks {

    /// strawberry fields
    public static RegistryObject<Block> STRAWBERRY_BLOSSOMS;
    public static RegistryObject<Block> STRAWBERRY_BLOSSOM_SAPLING;
    public static RegistryObject<Block> STRAWBERRY_LOG;
    public static RegistryObject<Block> STRIPPED_STRAWBERRY_LOG;
    public static RegistryObject<Block> STRAWBERRY_WOOD;
    public static RegistryObject<Block> STRIPPED_STRAWBERRY_WOOD;
    public static RegistryObject<Block> STRAWBERRY_PLANKS;
    public static RegistryObject<Block> STRAWBERRY_STAIRS;
    public static RegistryObject<Block> STRAWBERRY_SLAB;
    public static RegistryObject<Block> STRAWBERRY_FENCE;
    public static RegistryObject<Block> STRAWBERRY_FENCE_GATE;
    public static RegistryObject<Block> STRAWBERRY_BUTTON;
    public static RegistryObject<Block> STRAWBERRY_PRESSURE_PLATE;
    public static RegistryObject<Block> STRAWBERRY_TRAPDOOR;
    public static RegistryObject<Block> STRAWBERRY_DOOR;
    public static RegistryObject<Block> STRAWBERRY_SIGN;
    public static RegistryObject<Block> STRAWBERRY_WALL_SIGN;
    public static RegistryObject<Block> STRAWBERRY_HANGING_SIGN;
    public static RegistryObject<Block> STRAWBERRY_WALL_HANGING_SIGN;

    ///public static RegistryObject<Block> PINK_DAISIES;
    ///public static RegistryObject<Block> WILD_STRAWBERRY_BUSH;
    ///public static RegistryObject<Block> STRAWBERRY_BUSH;
    ///public static RegistryObject<Block> STRAWBERRY_CAKE;

    /// lavender meadow
    public static RegistryObject<Block> LAVENDER_BLOSSOMS;
    public static RegistryObject<Block> LAVENDER_BLOSSOM_SAPLING;
    public static RegistryObject<Block> LAVENDER_LOG;
    public static RegistryObject<Block> STRIPPED_LAVENDER_LOG;
    public static RegistryObject<Block> LAVENDER_WOOD;
    public static RegistryObject<Block> STRIPPED_LAVENDER_WOOD;
    public static RegistryObject<Block> LAVENDER_PLANKS;
    public static RegistryObject<Block> LAVENDER_STAIRS;
    public static RegistryObject<Block> LAVENDER_SLAB;
    public static RegistryObject<Block> LAVENDER_FENCE;
    public static RegistryObject<Block> LAVENDER_FENCE_GATE;
    public static RegistryObject<Block> LAVENDER_BUTTON;
    public static RegistryObject<Block> LAVENDER_PRESSURE_PLATE;
    public static RegistryObject<Block> LAVENDER_TRAPDOOR;
    public static RegistryObject<Block> LAVENDER_DOOR;
    public static RegistryObject<Block> LAVENDER_SIGN;
    public static RegistryObject<Block> LAVENDER_WALL_SIGN;
    public static RegistryObject<Block> LAVENDER_HANGING_SIGN;
    public static RegistryObject<Block> LAVENDER_WALL_HANGING_SIGN;

    ///public static RegistryObject<Block> LAVENDER;
    ///public static RegistryObject<Block> TALL_LAVENDER;
    ///public static RegistryObject<Block> BUNDLED_LAVENDER_BUDS;
    ///public static RegistryObject<Block> BUTTERFLY_BUSH_LEAVES;
    ///public static RegistryObject<Block> BUTTERFLY_BUSH;
    ///public static RegistryObject<Block> BUTTERFLY_NEST;
    ///public static RegistryObject<Block> CHRYSALIS;

    /// bamboo blossom forest
    public static RegistryObject<Block> PINK_CHERRY_BLOSSOMS;
    ///public static RegistryObject<Block> PINK_CHERRY_PETALS;
    public static RegistryObject<Block> PINK_CHERRY_BLOSSOM_SAPLING;
    public static RegistryObject<Block> WHITE_CHERRY_BLOSSOMS;
    ///public static RegistryObject<Block> WHITE_CHERRY_PETALS;
    public static RegistryObject<Block> WHITE_CHERRY_BLOSSOM_SAPLING;
    public static RegistryObject<Block> BLACK_CHERRY_LOG;
    public static RegistryObject<Block> STRIPPED_BLACK_CHERRY_LOG;
    public static RegistryObject<Block> BLACK_CHERRY_WOOD;
    public static RegistryObject<Block> STRIPPED_BLACK_CHERRY_WOOD;
    public static RegistryObject<Block> BLACK_CHERRY_PLANKS;
    public static RegistryObject<Block> BLACK_CHERRY_STAIRS;
    public static RegistryObject<Block> BLACK_CHERRY_SLAB;
    public static RegistryObject<Block> BLACK_CHERRY_FENCE;
    public static RegistryObject<Block> BLACK_CHERRY_FENCE_GATE;
    public static RegistryObject<Block> BLACK_CHERRY_BUTTON;
    public static RegistryObject<Block> BLACK_CHERRY_PRESSURE_PLATE;
    public static RegistryObject<Block> BLACK_CHERRY_TRAPDOOR;
    public static RegistryObject<Block> BLACK_CHERRY_DOOR;
    public static RegistryObject<Block> BLACK_CHERRY_SIGN;
    public static RegistryObject<Block> BLACK_CHERRY_WALL_SIGN;
    public static RegistryObject<Block> BLACK_CHERRY_HANGING_SIGN;
    public static RegistryObject<Block> BLACK_CHERRY_WALL_HANGING_SIGN;

    ///public static RegistryObject<Block> SPRING_BAMBOO;
    ///public static RegistryObject<Block> SPRING_BAMBOO_SAPLING;
    public static RegistryObject<Block> SPRING_BAMBOO_BLOCK;
    public static RegistryObject<Block> STRIPPED_SPRING_BAMBOO_BLOCK;
    public static RegistryObject<Block> SPRING_PLANKS;
    public static RegistryObject<Block> SPRING_MOSAIC;
    public static RegistryObject<Block> SPRING_STAIRS;
    public static RegistryObject<Block> SPRING_MOSAIC_STAIRS;
    public static RegistryObject<Block> SPRING_SLAB;
    public static RegistryObject<Block> SPRING_MOSAIC_SLAB;
    public static RegistryObject<Block> SPRING_FENCE;
    public static RegistryObject<Block> SPRING_FENCE_GATE;
    public static RegistryObject<Block> SPRING_BUTTON;
    public static RegistryObject<Block> SPRING_PRESSURE_PLATE;
    public static RegistryObject<Block> SPRING_TRAPDOOR;
    public static RegistryObject<Block> SPRING_DOOR;
    public static RegistryObject<Block> SPRING_SIGN;
    public static RegistryObject<Block> SPRING_WALL_SIGN;
    public static RegistryObject<Block> SPRING_HANGING_SIGN;
    public static RegistryObject<Block> SPRING_WALL_HANGING_SIGN;

    ///public static RegistryObject<Block> CHERRY_PLANT;
    ///public static RegistryObject<Block> CHERRY_PIE;
    ///public static RegistryObject<Block> PEONY_BUSH_LEAVES;
    ///public static RegistryObject<Block> PEONY_BUSH;

    /// autumnal grove
    public static RegistryObject<Block> MAPLE_LEAVES;
    ///public static RegistryObject<Block> MAPLE_LEAF_PILE;
    ///public static RegistryObject<Block> MAPLE_LEAF_LITTER;
    public static RegistryObject<Block> MAPLE_SAPLING;
    public static RegistryObject<Block> SPICED_MAPLE_LEAVES;
    ///public static RegistryObject<Block> SPICED_MAPLE_LEAF_PILE;
    ///public static RegistryObject<Block> SPICED_MAPLE_LEAF_LITTER;
    public static RegistryObject<Block> SPICED_MAPLE_SAPLING;
    public static RegistryObject<Block> ORANGE_MAPLE_LEAVES;
    ///public static RegistryObject<Block> ORANGE_MAPLE_LEAF_PILE;
    ///public static RegistryObject<Block> ORANGE_MAPLE_LEAF_LITTER;
    public static RegistryObject<Block> ORANGE_MAPLE_SAPLING;
    public static RegistryObject<Block> YELLOW_MAPLE_LEAVES;
    ///public static RegistryObject<Block> YELLOW_MAPLE_LEAF_PILE;
    ///public static RegistryObject<Block> YELLOW_MAPLE_LEAF_LITTER;
    public static RegistryObject<Block> YELLOW_MAPLE_SAPLING;
    public static RegistryObject<Block> MAPLE_LOG;
    public static RegistryObject<Block> WHITE_MAPLE_LOG;
    public static RegistryObject<Block> STRIPPED_MAPLE_LOG;
    public static RegistryObject<Block> MAPLE_WOOD;
    public static RegistryObject<Block> WHITE_MAPLE_WOOD;
    public static RegistryObject<Block> STRIPPED_MAPLE_WOOD;
    public static RegistryObject<Block> MAPLE_PLANKS;
    public static RegistryObject<Block> MAPLE_STAIRS;
    public static RegistryObject<Block> MAPLE_SLAB;
    public static RegistryObject<Block> MAPLE_FENCE;
    public static RegistryObject<Block> MAPLE_FENCE_GATE;
    public static RegistryObject<Block> MAPLE_BUTTON;
    public static RegistryObject<Block> MAPLE_PRESSURE_PLATE;
    public static RegistryObject<Block> MAPLE_TRAPDOOR;
    public static RegistryObject<Block> MAPLE_DOOR;
    public static RegistryObject<Block> MAPLE_SIGN;
    public static RegistryObject<Block> MAPLE_WALL_SIGN;
    public static RegistryObject<Block> MAPLE_HANGING_SIGN;
    public static RegistryObject<Block> MAPLE_WALL_HANGING_SIGN;

    ///public static RegistryObject<Block> MAPLE_PANCAKES;
    ///public static RegistryObject<Block> ASTER;
    ///public static RegistryObject<Block> GOLDENROD;

    /// lush oasis
    public static RegistryObject<Block> GRASSY_LUSH_SAND;
    ///public static RegistryObject<Block> LUSH_GRASS;
    ///public static RegistryObject<Block> TALL_LUSH_GRASS;
    public static RegistryObject<Block> LUSH_SAND;
    public static RegistryObject<Block> LUSH_SANDSTONE;
    public static RegistryObject<Block> LUSH_SANDSTONE_STAIRS;
    public static RegistryObject<Block> LUSH_SANDSTONE_SLAB;
    public static RegistryObject<Block> LUSH_SANDSTONE_WALL;
    public static RegistryObject<Block> CHISELED_LUSH_SANDSTONE;
    public static RegistryObject<Block> CUT_LUSH_SANDSTONE;
    public static RegistryObject<Block> CUT_LUSH_SANDSTONE_SLAB;
    public static RegistryObject<Block> SMOOTH_LUSH_SANDSTONE;
    public static RegistryObject<Block> SMOOTH_LUSH_SANDSTONE_STAIRS;
    public static RegistryObject<Block> SMOOTH_LUSH_SANDSTONE_SLAB;

    public static RegistryObject<Block> PEACH_LEAVES;
    public static RegistryObject<Block> PEACH_SAPLING;
    public static RegistryObject<Block> PEACH_LOG;
    public static RegistryObject<Block> STRIPPED_PEACH_LOG;
    public static RegistryObject<Block> PEACH_WOOD;
    public static RegistryObject<Block> STRIPPED_PEACH_WOOD;
    public static RegistryObject<Block> PEACH_PLANKS;
    public static RegistryObject<Block> PEACH_STAIRS;
    public static RegistryObject<Block> PEACH_SLAB;
    public static RegistryObject<Block> PEACH_FENCE;
    public static RegistryObject<Block> PEACH_FENCE_GATE;
    public static RegistryObject<Block> PEACH_BUTTON;
    public static RegistryObject<Block> PEACH_PRESSURE_PLATE;
    public static RegistryObject<Block> PEACH_TRAPDOOR;
    public static RegistryObject<Block> PEACH_DOOR;
    public static RegistryObject<Block> PEACH_SIGN;
    public static RegistryObject<Block> PEACH_WALL_SIGN;
    public static RegistryObject<Block> PEACH_HANGING_SIGN;
    public static RegistryObject<Block> PEACH_WALL_HANGING_SIGN;

    ///public static RegistryObject<Block> PEACH_PLANT;
    ///public static RegistryObject<Block> PEACH_PIE;
    ///public static RegistryObject<Block> DESERT_SHRUB;
    ///public static RegistryObject<Block> DESERT_GRASS;
    ///public static RegistryObject<Block> TALL_DESERT_GRASS;
    ///public static RegistryObject<Block> DESERT_LILY;
    ///public static RegistryObject<Block> WILDFLOWER;
    ///public static RegistryObject<Block> SAGUARO_CACTUS;
    ///public static RegistryObject<Block> SAGUARO_BLOSSOM;
    ///public static RegistryObject<Block> PRICKLY_CACTUS;
    ///public static RegistryObject<Block> PRICKLY_BLOSSOM;
    ///public static RegistryObject<Block> PRICKLY_PEAR;

    /// lagoon
    public static RegistryObject<Block> SEA_SHRUB_LEAVES;
    public static RegistryObject<Block> SEA_SHRUB;
    public static RegistryObject<Block> SEA_FOAM_LOG;
    public static RegistryObject<Block> STRIPPED_SEA_FOAM_LOG;
    public static RegistryObject<Block> SEA_FOAM_WOOD;
    public static RegistryObject<Block> STRIPPED_SEA_FOAM_WOOD;
    public static RegistryObject<Block> SEA_FOAM_PLANKS;
    public static RegistryObject<Block> SEA_FOAM_STAIRS;
    public static RegistryObject<Block> SEA_FOAM_SLAB;
    public static RegistryObject<Block> SEA_FOAM_FENCE;
    public static RegistryObject<Block> SEA_FOAM_FENCE_GATE;
    public static RegistryObject<Block> SEA_FOAM_BUTTON;
    public static RegistryObject<Block> SEA_FOAM_PRESSURE_PLATE;
    public static RegistryObject<Block> SEA_FOAM_TRAPDOOR;
    public static RegistryObject<Block> SEA_FOAM_DOOR;
    public static RegistryObject<Block> SEA_FOAM_SIGN;
    public static RegistryObject<Block> SEA_FOAM_WALL_SIGN;
    public static RegistryObject<Block> SEA_FOAM_HANGING_SIGN;
    public static RegistryObject<Block> SEA_FOAM_WALL_HANGING_SIGN;

    ///public static RegistryObject<Block> BEACH_GRASS;
    ///public static RegistryObject<Block> TALL_BEACH_GRASS;
    ///public static RegistryObject<Block> MILKWEED;
    ///public static RegistryObject<Block> SEA_THRIFT;
    ///public static RegistryObject<Block> SEA_OATS;
    ///public static RegistryObject<Block> SEA_FOAM;

    /// tropics
    public static RegistryObject<Block> TROPICAL_LEAVES;
    public static RegistryObject<Block> TROPICAL_SAPLING;
    public static RegistryObject<Block> TROPICAL_LOG;
    public static RegistryObject<Block> STRIPPED_TROPICAL_LOG;
    public static RegistryObject<Block> TROPICAL_WOOD;
    public static RegistryObject<Block> STRIPPED_TROPICAL_WOOD;
    public static RegistryObject<Block> TROPICAL_PLANKS;
    public static RegistryObject<Block> TROPICAL_STAIRS;
    public static RegistryObject<Block> TROPICAL_SLAB;
    public static RegistryObject<Block> TROPICAL_FENCE;
    public static RegistryObject<Block> TROPICAL_FENCE_GATE;
    public static RegistryObject<Block> TROPICAL_BUTTON;
    public static RegistryObject<Block> TROPICAL_PRESSURE_PLATE;
    public static RegistryObject<Block> TROPICAL_TRAPDOOR;
    public static RegistryObject<Block> TROPICAL_DOOR;
    public static RegistryObject<Block> TROPICAL_SIGN;
    public static RegistryObject<Block> TROPICAL_WALL_SIGN;
    public static RegistryObject<Block> TROPICAL_HANGING_SIGN;
    public static RegistryObject<Block> TROPICAL_WALL_HANGING_SIGN;

    public static RegistryObject<Block> VANILLA_LEAVES;
    public static RegistryObject<Block> VANILLA_SAPLING;
    public static RegistryObject<Block> VANILLA_LOG;
    public static RegistryObject<Block> STRIPPED_VANILLA_LOG;
    public static RegistryObject<Block> VANILLA_WOOD;
    public static RegistryObject<Block> STRIPPED_VANILLA_WOOD;
    public static RegistryObject<Block> VANILLA_PLANKS;
    public static RegistryObject<Block> VANILLA_STAIRS;
    public static RegistryObject<Block> VANILLA_SLAB;
    public static RegistryObject<Block> VANILLA_FENCE;
    public static RegistryObject<Block> VANILLA_FENCE_GATE;
    public static RegistryObject<Block> VANILLA_BUTTON;
    public static RegistryObject<Block> VANILLA_PRESSURE_PLATE;
    public static RegistryObject<Block> VANILLA_TRAPDOOR;
    public static RegistryObject<Block> VANILLA_DOOR;
    public static RegistryObject<Block> VANILLA_SIGN;
    public static RegistryObject<Block> VANILLA_WALL_SIGN;
    public static RegistryObject<Block> VANILLA_HANGING_SIGN;
    public static RegistryObject<Block> VANILLA_WALL_HANGING_SIGN;

    ///public static RegistryObject<Block> TROPICAL_VINES;
    ///public static RegistryObject<Block> JUNGLE_SHRUB;
    ///public static RegistryObject<Block> JUNGLE_GRASS;
    ///public static RegistryObject<Block> TALL_JUNGLE_GRASS;
    ///public static RegistryObject<Block> BANANA_LEAF_PLANT;
    ///public static RegistryObject<Block> HYDRANGEA_BUSH_LEAVES;
    ///public static RegistryObject<Block> HYDRANGEA_BUSH;
    ///public static RegistryObject<Block> HIBISCUS;
    ///public static RegistryObject<Block> VANILLA_ORCHID;
    ///public static RegistryObject<Block> VANILLA_CAKE;
    ///public static RegistryObject<Block> CHOCOLATE_CAKE;

    /// frosted cakes
    ///public static RegistryObject<Block> PINK_FROSTED_CAKE;
    ///public static RegistryObject<Block> ORANGE_FROSTED_CAKE;
    ///public static RegistryObject<Block> YELLOW_FROSTED_CAKE;
    ///public static RegistryObject<Block> LIME_FROSTED_CAKE;
    ///public static RegistryObject<Block> CYAN_FROSTED_CAKE;
    ///public static RegistryObject<Block> PURPLE_FROSTED_CAKE;
    ///public static RegistryObject<Block> RAINBOW_FROSTED_CAKE;

    /// potted plants
    ///public static RegistryObject<Block> POTTED_STRAWBERRY_SAPLING;
    ///public static RegistryObject<Block> POTTED_STRAWBERRY_BUSH;
    ///public static RegistryObject<Block> POTTED_PINK_DAISIES;
    ///public static RegistryObject<Block> POTTED_LAVENDER_SAPLING;
    ///public static RegistryObject<Block> POTTED_LAVENDER;
    ///public static RegistryObject<Block> POTTED_BUTTERFLY_BUSH;
    ///public static RegistryObject<Block> POTTED_PINK_CHERRY_BLOSSOM_SAPLING;
    ///public static RegistryObject<Block> POTTED_WHITE_CHERRY_BLOSSOM_SAPLING;
    ///public static RegistryObject<Block> POTTED_SPRING_BAMBOO;
    ///public static RegistryObject<Block> POTTED_STRIPPED_SPRING_BAMBOO;
    ///public static RegistryObject<Block> POTTED_PEONY_BUSH;
    ///public static RegistryObject<Block> POTTED_MAPLE_SAPLING;
    ///public static RegistryObject<Block> POTTED_SPICED_MAPLE_SAPLING;
    ///public static RegistryObject<Block> POTTED_ORANGE_MAPLE_SAPLING;
    ///public static RegistryObject<Block> POTTED_YELLOW_MAPLE_SAPLING;
    ///public static RegistryObject<Block> POTTED_ASTER;
    ///public static RegistryObject<Block> POTTED_GOLDENROD;
    ///public static RegistryObject<Block> POTTED_PEACH_SAPLING;
    ///public static RegistryObject<Block> POTTED_DESERT_SHRUB;
    ///public static RegistryObject<Block> POTTED_DESERT_LILY;
    ///public static RegistryObject<Block> POTTED_WILDFLOWER;
    ///public static RegistryObject<Block> POTTED_SAGUARO_CACTUS;
    ///public static RegistryObject<Block> POTTED_PRICKLY_CACTUS;
    ///public static RegistryObject<Block> POTTED_SEA_SHRUB;
    ///public static RegistryObject<Block> POTTED_MILKWEED;
    ///public static RegistryObject<Block> POTTED_SEA_THRIFT;
    ///public static RegistryObject<Block> POTTED_SEA_OATS;
    ///public static RegistryObject<Block> POTTED_TROPICAL_SAPLING;
    ///public static RegistryObject<Block> POTTED_VANILLA_SAPLING;
    ///public static RegistryObject<Block> POTTED_JUNGLE_SHRUB;
    ///public static RegistryObject<Block> POTTED_HYDRANGEA_BUSH;
    ///public static RegistryObject<Block> POTTED_HIBISCUS;

    public static void registerBlocks() {
        /// strawberry fields
        STRAWBERRY_BLOSSOMS = register("strawberry_blossoms", () -> new LeavesBlock(leafProperties(SoundType.AZALEA_LEAVES)));
        STRAWBERRY_BLOSSOM_SAPLING = register("strawberry_blossom_sapling", () -> sapling(new MysticTreeGrowers(TreeFeatures.OAK)));///TreeFeatures.OAK)));
        STRAWBERRY_LOG = register("strawberry_log", () -> log(MapColor.COLOR_PINK, MapColor.COLOR_BROWN));
        STRIPPED_STRAWBERRY_LOG = register("stripped_strawberry_log", () -> log(MapColor.COLOR_PINK));
        STRAWBERRY_WOOD = register("strawberry_wood", () -> log(MapColor.COLOR_PINK, MapColor.COLOR_BROWN));
        STRIPPED_STRAWBERRY_WOOD = register("stripped_strawberry_wood", () -> log(MapColor.COLOR_PINK));
        STRAWBERRY_PLANKS = register("strawberry_planks", () -> planks(MapColor.COLOR_PINK));
        STRAWBERRY_STAIRS = register("strawberry_stairs", () -> stairs(STRAWBERRY_PLANKS.get()));
        STRAWBERRY_SLAB = register("strawberry_slab", () -> slab(STRAWBERRY_PLANKS.get()));
        STRAWBERRY_FENCE = register("strawberry_fence", () -> fence(STRAWBERRY_PLANKS.get()));
        STRAWBERRY_FENCE_GATE = register("strawberry_fence_gate", () -> fenceGate(STRAWBERRY_PLANKS.get(), MysticWoodTypes.STRAWBERRY));
        STRAWBERRY_BUTTON = register("strawberry_button", () -> button(MysticBlockSetTypes.STRAWBERRY));
        STRAWBERRY_PRESSURE_PLATE = register("strawberry_pressure_plate", () -> pressurePlate(STRAWBERRY_PLANKS.get(), MysticBlockSetTypes.STRAWBERRY));
        STRAWBERRY_TRAPDOOR = register("strawberry_trapdoor", () -> trapdoor(STRAWBERRY_PLANKS.get(), MysticBlockSetTypes.STRAWBERRY));
        STRAWBERRY_DOOR = register("strawberry_door", () -> door(STRAWBERRY_PLANKS.get(), MysticBlockSetTypes.STRAWBERRY));
        STRAWBERRY_SIGN = register("strawberry_sign", () -> sign(STRAWBERRY_PLANKS.get(), MysticWoodTypes.STRAWBERRY));
        STRAWBERRY_WALL_SIGN = register("strawberry_wall_sign", () -> wallSign(STRAWBERRY_SIGN.get(), MysticWoodTypes.STRAWBERRY));
        STRAWBERRY_HANGING_SIGN = register("strawberry_hanging_sign", () -> hangingSign(STRAWBERRY_PLANKS.get(), MysticWoodTypes.STRAWBERRY));
        STRAWBERRY_WALL_HANGING_SIGN = register("strawberry_wall_hanging_sign", () -> wallHangingSign(STRAWBERRY_HANGING_SIGN.get(), MysticWoodTypes.STRAWBERRY));

        /// lavender meadow
        LAVENDER_BLOSSOMS = register("lavender_blossoms", () -> leaves(SoundType.AZALEA_LEAVES));
        LAVENDER_BLOSSOM_SAPLING = register("lavender_blossom_sapling", () -> sapling(new MysticTreeGrowers(TreeFeatures.OAK)));///MysticTreeFeatures.LAVENDER_TREE)));
        LAVENDER_LOG = register("lavender_log", () -> log(MapColor.COLOR_PURPLE, MapColor.COLOR_BROWN));
        STRIPPED_LAVENDER_LOG = register("stripped_lavender_log", () -> log(MapColor.COLOR_PURPLE));
        LAVENDER_WOOD = register("lavender_wood", () -> log(MapColor.COLOR_PURPLE, MapColor.COLOR_BROWN));
        STRIPPED_LAVENDER_WOOD = register("stripped_lavender_wood", () -> log(MapColor.COLOR_PURPLE));
        LAVENDER_PLANKS = register("lavender_planks", () -> planks(MapColor.COLOR_PURPLE));
        LAVENDER_STAIRS = register("lavender_stairs", () -> stairs(LAVENDER_PLANKS.get()));
        LAVENDER_SLAB = register("lavender_slab", () -> slab(LAVENDER_PLANKS.get()));
        LAVENDER_FENCE = register("lavender_fence", () -> fence(LAVENDER_PLANKS.get()));
        LAVENDER_FENCE_GATE = register("lavender_fence_gate", () -> fenceGate(LAVENDER_PLANKS.get(), MysticWoodTypes.LAVENDER));
        LAVENDER_BUTTON = register("lavender_button", () -> button(MysticBlockSetTypes.LAVENDER));
        LAVENDER_PRESSURE_PLATE = register("lavender_pressure_plate", () -> pressurePlate(LAVENDER_PLANKS.get(), MysticBlockSetTypes.LAVENDER));
        LAVENDER_TRAPDOOR = register("lavender_trapdoor", () -> trapdoor(LAVENDER_PLANKS.get(), MysticBlockSetTypes.LAVENDER));
        LAVENDER_DOOR = register("lavender_door", () -> door(LAVENDER_PLANKS.get(), MysticBlockSetTypes.LAVENDER));
        LAVENDER_SIGN = register("lavender_sign", () -> sign(LAVENDER_PLANKS.get(), MysticWoodTypes.LAVENDER));
        LAVENDER_WALL_SIGN = register("lavender_wall_sign", () -> wallSign(LAVENDER_SIGN.get(), MysticWoodTypes.LAVENDER));
        LAVENDER_HANGING_SIGN = register("lavender_hanging_sign", () -> hangingSign(LAVENDER_PLANKS.get(), MysticWoodTypes.LAVENDER));
        LAVENDER_WALL_HANGING_SIGN = register("lavender_wall_hanging_sign", () -> wallHangingSign(LAVENDER_HANGING_SIGN.get(), MysticWoodTypes.LAVENDER));

        /// bamboo blossom forest
        PINK_CHERRY_BLOSSOMS = register("pink_cherry_blossoms", () -> new LeavesBlock(leafProperties(SoundType.CHERRY_LEAVES)));
        PINK_CHERRY_BLOSSOM_SAPLING = register("pink_cherry_blossom_sapling", () -> sapling(new MysticTreeGrowers(TreeFeatures.OAK)));///MysticTreeFeatures.PINK_CHERRY_TREE), SoundType.CHERRY_SAPLING));
        WHITE_CHERRY_BLOSSOMS = register("white_cherry_blossoms", () -> new LeavesBlock(leafProperties(SoundType.CHERRY_LEAVES)));
        WHITE_CHERRY_BLOSSOM_SAPLING = register("white_cherry_blossom_sapling", () -> sapling(new MysticTreeGrowers(TreeFeatures.OAK)));///MysticTreeFeatures.WHITE_CHERRY_TREE), SoundType.CHERRY_SAPLING));
        BLACK_CHERRY_LOG = register("black_cherry_log", () -> log(MapColor.COLOR_MAGENTA, MapColor.TERRACOTTA_MAGENTA, SoundType.CHERRY_WOOD));
        STRIPPED_BLACK_CHERRY_LOG = register("stripped_black_cherry_log", () -> log(MapColor.COLOR_MAGENTA, SoundType.CHERRY_WOOD));
        BLACK_CHERRY_WOOD = register("black_cherry_wood", () -> log(MapColor.TERRACOTTA_MAGENTA, SoundType.CHERRY_WOOD));
        STRIPPED_BLACK_CHERRY_WOOD = register("stripped_black_cherry_wood", () -> log(MapColor.COLOR_MAGENTA, SoundType.CHERRY_WOOD));
        BLACK_CHERRY_PLANKS = register("black_cherry_planks", () -> planks(MapColor.COLOR_MAGENTA, SoundType.CHERRY_WOOD));
        BLACK_CHERRY_STAIRS = register("black_cherry_stairs", () -> stairs(BLACK_CHERRY_PLANKS.get()));
        BLACK_CHERRY_SLAB = register("black_cherry_slab", () -> slab(BLACK_CHERRY_PLANKS.get()));
        BLACK_CHERRY_FENCE = register("black_cherry_fence", () -> fence(BLACK_CHERRY_PLANKS.get()));
        BLACK_CHERRY_FENCE_GATE = register("black_cherry_fence_gate", () -> fenceGate(BLACK_CHERRY_PLANKS.get(), MysticWoodTypes.BLACK_CHERRY));
        BLACK_CHERRY_BUTTON = register("black_cherry_button", () -> button(MysticBlockSetTypes.BLACK_CHERRY));
        BLACK_CHERRY_PRESSURE_PLATE = register("black_cherry_pressure_plate", () -> pressurePlate(BLACK_CHERRY_PLANKS.get(), MysticBlockSetTypes.BLACK_CHERRY));
        BLACK_CHERRY_TRAPDOOR = register("black_cherry_trapdoor", () -> trapdoor(BLACK_CHERRY_PLANKS.get(), MysticBlockSetTypes.BLACK_CHERRY));
        BLACK_CHERRY_DOOR = register("black_cherry_door", () -> door(BLACK_CHERRY_PLANKS.get(), MysticBlockSetTypes.BLACK_CHERRY));
        BLACK_CHERRY_SIGN = register("black_cherry_sign", () -> sign(BLACK_CHERRY_PLANKS.get(), MysticWoodTypes.BLACK_CHERRY));
        BLACK_CHERRY_WALL_SIGN = register("black_cherry_wall_sign", () -> wallSign(BLACK_CHERRY_SIGN.get(), MysticWoodTypes.BLACK_CHERRY));
        BLACK_CHERRY_HANGING_SIGN = register("black_cherry_hanging_sign", () -> hangingSign(BLACK_CHERRY_PLANKS.get(), MysticWoodTypes.BLACK_CHERRY));
        BLACK_CHERRY_WALL_HANGING_SIGN = register("black_cherry_wall_hanging_sign", () -> wallHangingSign(BLACK_CHERRY_HANGING_SIGN.get(), MysticWoodTypes.BLACK_CHERRY));

        ///SPRING_BAMBOO_SAPLING = register("spring_bamboo_sapling", () -> new SpringBambooSaplingBlock(bambooProperties(SoundType.BAMBOO_SAPLING)));
        ///SPRING_BAMBOO = register("spring_bamboo", () -> new SpringBambooStalkBlock(bambooProperties(SoundType.BAMBOO)));
        SPRING_BAMBOO_BLOCK = register("spring_bamboo_block", () -> log(MapColor.COLOR_LIGHT_GREEN, MapColor.COLOR_GREEN, SoundType.BAMBOO_WOOD));
        STRIPPED_SPRING_BAMBOO_BLOCK = register("stripped_spring_bamboo_block", () -> log(MapColor.COLOR_LIGHT_GREEN, SoundType.BAMBOO_WOOD));
        SPRING_PLANKS = register("spring_planks", () -> planks(MapColor.COLOR_LIGHT_GREEN, SoundType.BAMBOO_WOOD));
        SPRING_MOSAIC = register("spring_mosaic", () -> planks(MapColor.COLOR_LIGHT_GREEN));
        SPRING_STAIRS = register("spring_stairs", () -> stairs(SPRING_PLANKS.get()));
        SPRING_MOSAIC_STAIRS = register("spring_mosaic_stairs", () -> stairs(SPRING_PLANKS.get()));
        SPRING_SLAB = register("spring_slab", () -> slab(SPRING_PLANKS.get()));
        SPRING_MOSAIC_SLAB = register("spring_mosaic_slab", () -> slab(SPRING_PLANKS.get()));
        SPRING_FENCE = register("spring_fence", () -> fence(SPRING_PLANKS.get()));
        SPRING_FENCE_GATE = register("spring_fence_gate", () -> fenceGate(SPRING_PLANKS.get(), MysticWoodTypes.SPRING));
        SPRING_BUTTON = register("spring_button", () -> button(MysticBlockSetTypes.SPRING));
        SPRING_PRESSURE_PLATE = register("spring_pressure_plate", () -> pressurePlate(SPRING_PLANKS.get(), MysticBlockSetTypes.SPRING));
        SPRING_TRAPDOOR = register("spring_trapdoor", () -> trapdoor(SPRING_PLANKS.get(), MysticBlockSetTypes.SPRING));
        SPRING_DOOR = register("spring_door", () -> door(SPRING_PLANKS.get(), MysticBlockSetTypes.SPRING));
        SPRING_SIGN = register("spring_sign", () -> sign(SPRING_PLANKS.get(), MysticWoodTypes.SPRING));
        SPRING_WALL_SIGN = register("spring_wall_sign", () -> wallSign(SPRING_SIGN.get(), MysticWoodTypes.SPRING));
        SPRING_HANGING_SIGN = register("spring_hanging_sign", () -> hangingSign(SPRING_PLANKS.get(), MysticWoodTypes.SPRING));
        SPRING_WALL_HANGING_SIGN = register("spring_wall_hanging_sign", () -> wallHangingSign(SPRING_HANGING_SIGN.get(), MysticWoodTypes.SPRING));

        /// lush oasis
        LUSH_SAND = register("lush_sand", () -> new SandBlock(000000, BlockBehaviour.Properties.of().mapColor(MapColor.SAND).instrument(NoteBlockInstrument.SNARE).strength(0.5F).sound(SoundType.SAND)));
        GRASSY_LUSH_SAND = register("grassy_lush_sand", () -> new SandBlock(000000, copy(LUSH_SAND.get())));
        LUSH_SANDSTONE = register("lush_sandstone", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.SAND).instrument(NoteBlockInstrument.BASEDRUM).requiresCorrectToolForDrops().strength(0.8F)));
        LUSH_SANDSTONE_STAIRS = register("lush_sandstone_stairs", () -> stairs(LUSH_SANDSTONE.get()));
        LUSH_SANDSTONE_SLAB = register("lush_sandstone_slab", () -> slab(LUSH_SANDSTONE.get()));
        LUSH_SANDSTONE_WALL = register("lush_sandstone_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(LUSH_SANDSTONE.get()).forceSolidOn()));
        CHISELED_LUSH_SANDSTONE = register("chiseled_lush_sandstone", () -> new Block(copy(LUSH_SANDSTONE.get())));
        CUT_LUSH_SANDSTONE = register("cut_lush_sandstone", () -> new Block(copy(LUSH_SANDSTONE.get())));
        CUT_LUSH_SANDSTONE_SLAB = register("cut_lush_sandstone_slab", () -> new SlabBlock(copy(LUSH_SANDSTONE.get()).strength(2.0F, 6.0F)));
        SMOOTH_LUSH_SANDSTONE = register("smooth_lush_sandstone", () -> new Block(copy(LUSH_SANDSTONE.get()).strength(2.0F, 6.0F)));
        SMOOTH_LUSH_SANDSTONE_STAIRS = register("smooth_lush_sandstone_stairs", () -> stairs(SMOOTH_LUSH_SANDSTONE.get()));
        SMOOTH_LUSH_SANDSTONE_SLAB = register("smooth_lush_sandstone_slab", () -> slab(SMOOTH_LUSH_SANDSTONE.get()));

        PEACH_LEAVES = register("peach_leaves", () -> leaves(SoundType.AZALEA_LEAVES));
        PEACH_SAPLING = register("peach_sapling", () -> sapling(new MysticTreeGrowers(TreeFeatures.OAK)));///MysticTreeFeatures.PEACH_TREE)));
        PEACH_LOG = register("peach_log", () -> log(MapColor.SAND, MapColor.COLOR_BROWN));
        STRIPPED_PEACH_LOG = register("stripped_peach_log", () -> log(MapColor.SAND));
        PEACH_WOOD = register("peach_wood", () -> log(MapColor.SAND, MapColor.COLOR_BROWN));
        STRIPPED_PEACH_WOOD = register("stripped_peach_wood", () -> log(MapColor.SAND));
        PEACH_PLANKS = register("peach_planks", () -> planks(MapColor.SAND));
        PEACH_STAIRS = register("peach_stairs", () -> stairs(PEACH_PLANKS.get()));
        PEACH_SLAB = register("peach_slab", () -> slab(PEACH_PLANKS.get()));
        PEACH_FENCE = register("peach_fence", () -> fence(PEACH_PLANKS.get()));
        PEACH_FENCE_GATE = register("peach_fence_gate", () -> fenceGate(PEACH_PLANKS.get(), MysticWoodTypes.PEACH));
        PEACH_BUTTON = register("peach_button", () -> button(MysticBlockSetTypes.PEACH));
        PEACH_PRESSURE_PLATE = register("peach_pressure_plate", () -> pressurePlate(PEACH_PLANKS.get(), MysticBlockSetTypes.PEACH));
        PEACH_TRAPDOOR = register("peach_trapdoor", () -> trapdoor(PEACH_PLANKS.get(), MysticBlockSetTypes.PEACH));
        PEACH_DOOR = register("peach_door", () -> door(PEACH_PLANKS.get(), MysticBlockSetTypes.PEACH));
        PEACH_SIGN = register("peach_sign", () -> sign(PEACH_PLANKS.get(), MysticWoodTypes.PEACH));
        PEACH_WALL_SIGN = register("peach_wall_sign", () -> wallSign(PEACH_SIGN.get(), MysticWoodTypes.PEACH));
        PEACH_HANGING_SIGN = register("peach_hanging_sign", () -> hangingSign(PEACH_PLANKS.get(), MysticWoodTypes.PEACH));
        PEACH_WALL_HANGING_SIGN = register("peach_wall_hanging_sign", () -> wallHangingSign(PEACH_HANGING_SIGN.get(), MysticWoodTypes.PEACH));

        /// autumnal grove
        MAPLE_LEAVES = register("maple_leaves", () -> new LeavesBlock(leafProperties(SoundType.AZALEA_LEAVES)));
        ///MAPLE_LEAF_PILE = register("maple_leaf_pile", () -> leafLitter(MapColor.GRASS));
        ///MAPLE_LEAF_LITTER = register("maple_leaf_litter", () -> leafLitter(MapColor.GRASS));
        MAPLE_SAPLING = register("maple_sapling", () -> sapling(new MysticTreeGrowers(TreeFeatures.OAK)));///MysticTreeFeatures.MAPLE_TREE)));
        SPICED_MAPLE_LEAVES = register("spiced_maple_leaves", () -> new LeavesBlock(leafProperties(SoundType.AZALEA_LEAVES)));
        ///SPICED_MAPLE_LEAF_PILE = register("spiced_maple_leaf_pile", () -> leafLitter(MapColor.TERRACOTTA_ORANGE));
        ///SPICED_MAPLE_LEAF_LITTER = register("spiced_maple_leaf_litter", () -> leafLitter(MapColor.TERRACOTTA_ORANGE));
        SPICED_MAPLE_SAPLING = register("spiced_maple_sapling", () -> sapling(new MysticTreeGrowers(TreeFeatures.OAK)));///MysticTreeFeatures.ORANGE_MAPLE_TREE)));
        ORANGE_MAPLE_LEAVES = register("orange_maple_leaves", () -> new LeavesBlock(leafProperties(SoundType.AZALEA_LEAVES)));
        ///ORANGE_MAPLE_LEAF_PILE = register("orange_maple_leaf_pile", () -> leafLitter(MapColor.TERRACOTTA_ORANGE));
        ///ORANGE_MAPLE_LEAF_LITTER = register("orange_maple_leaf_litter", () -> leafLitter(MapColor.TERRACOTTA_ORANGE));
        ORANGE_MAPLE_SAPLING = register("orange_maple_sapling", () -> sapling(new MysticTreeGrowers(TreeFeatures.OAK)));///MysticTreeFeatures.ORANGE_MAPLE_TREE)));
        YELLOW_MAPLE_LEAVES = register("yellow_maple_leaves", () -> new LeavesBlock(leafProperties(SoundType.AZALEA_LEAVES)));
        ///YELLOW_MAPLE_LEAF_PILE = register("yellow_maple_leaf_pile", () -> leafLitter(MapColor.TERRACOTTA_YELLOW));
        ///YELLOW_MAPLE_LEAF_LITTER = register("yellow_maple_leaf_litter", () -> leafLitter(MapColor.TERRACOTTA_YELLOW));
        YELLOW_MAPLE_SAPLING = register("yellow_maple_sapling", () -> sapling(new MysticTreeGrowers(TreeFeatures.OAK)));///MysticTreeFeatures.YELLOW_MAPLE_TREE)));
        MAPLE_LOG = register("maple_log", () -> log(MapColor.COLOR_ORANGE, MapColor.COLOR_BROWN));
        WHITE_MAPLE_LOG = register("white_maple_log", () -> log(MapColor.COLOR_ORANGE, MapColor.TERRACOTTA_WHITE));
        STRIPPED_MAPLE_LOG = register("stripped_maple_log", () -> log(MapColor.COLOR_ORANGE));
        MAPLE_WOOD = register("maple_wood", () -> log(MapColor.COLOR_ORANGE, MapColor.COLOR_BROWN));
        WHITE_MAPLE_WOOD = register("white_maple_wood", () -> log(MapColor.TERRACOTTA_WHITE, MapColor.TERRACOTTA_WHITE));
        STRIPPED_MAPLE_WOOD = register("stripped_maple_wood", () -> log(MapColor.COLOR_ORANGE));
        MAPLE_PLANKS = register("maple_planks", () -> planks(MapColor.COLOR_ORANGE));
        MAPLE_STAIRS = register("maple_stairs", () -> stairs(MAPLE_PLANKS.get()));
        MAPLE_SLAB = register("maple_slab", () -> slab(MAPLE_PLANKS.get()));
        MAPLE_FENCE = register("maple_fence", () -> fence(MAPLE_PLANKS.get()));
        MAPLE_FENCE_GATE = register("maple_fence_gate", () -> fenceGate(MAPLE_PLANKS.get(), MysticWoodTypes.MAPLE));
        MAPLE_BUTTON = register("maple_button", () -> button(MysticBlockSetTypes.MAPLE));
        MAPLE_PRESSURE_PLATE = register("maple_pressure_plate", () -> pressurePlate(MAPLE_PLANKS.get(), MysticBlockSetTypes.MAPLE));
        MAPLE_TRAPDOOR = register("maple_trapdoor", () -> trapdoor(MAPLE_PLANKS.get(), MysticBlockSetTypes.MAPLE));
        MAPLE_DOOR = register("maple_door", () -> door(MAPLE_PLANKS.get(), MysticBlockSetTypes.MAPLE));
        MAPLE_SIGN = register("maple_sign", () -> sign(MAPLE_PLANKS.get(), MysticWoodTypes.MAPLE));
        MAPLE_WALL_SIGN = register("maple_wall_sign", () -> wallSign(MAPLE_SIGN.get(), MysticWoodTypes.MAPLE));
        MAPLE_HANGING_SIGN = register("maple_hanging_sign", () -> hangingSign(MAPLE_PLANKS.get(), MysticWoodTypes.MAPLE));
        MAPLE_WALL_HANGING_SIGN = register("maple_wall_hanging_sign", () -> wallHangingSign(MAPLE_HANGING_SIGN.get(), MysticWoodTypes.MAPLE));

        /// lagoon
        SEA_SHRUB_LEAVES = register("sea_shrub_leaves", () -> leaves(SoundType.GRASS));
        SEA_SHRUB = register("sea_shrub", () -> shrub(new MysticTreeGrowers(TreeFeatures.OAK)));///MysticTreeFeatures.SEA_SHRUB)));
        SEA_FOAM_LOG = register("sea_foam_log", () -> log(MapColor.COLOR_CYAN, MapColor.COLOR_BROWN));
        STRIPPED_SEA_FOAM_LOG = register("stripped_sea_foam_log", () -> log(MapColor.COLOR_CYAN));
        SEA_FOAM_WOOD = register("sea_foam_wood", () -> log(MapColor.COLOR_CYAN, MapColor.COLOR_BROWN));
        STRIPPED_SEA_FOAM_WOOD = register("stripped_sea_foam_wood", () -> log(MapColor.COLOR_CYAN));
        SEA_FOAM_PLANKS = register("sea_foam_planks", () -> planks(MapColor.COLOR_CYAN));
        SEA_FOAM_STAIRS = register("sea_foam_stairs", () -> stairs(SEA_FOAM_PLANKS.get()));
        SEA_FOAM_SLAB = register("sea_foam_slab", () -> slab(SEA_FOAM_PLANKS.get()));
        SEA_FOAM_FENCE = register("sea_foam_fence", () -> fence(SEA_FOAM_PLANKS.get()));
        SEA_FOAM_FENCE_GATE = register("sea_foam_fence_gate", () -> fenceGate(SEA_FOAM_PLANKS.get(), MysticWoodTypes.SEA_FOAM));
        SEA_FOAM_BUTTON = register("sea_foam_button", () -> button(MysticBlockSetTypes.SEA_FOAM));
        SEA_FOAM_PRESSURE_PLATE = register("sea_foam_pressure_plate", () -> pressurePlate(SEA_FOAM_PLANKS.get(), MysticBlockSetTypes.SEA_FOAM));
        SEA_FOAM_TRAPDOOR = register("sea_foam_trapdoor", () -> trapdoor(SEA_FOAM_PLANKS.get(), MysticBlockSetTypes.SEA_FOAM));
        SEA_FOAM_DOOR = register("sea_foam_door", () -> door(SEA_FOAM_PLANKS.get(), MysticBlockSetTypes.SEA_FOAM));
        SEA_FOAM_SIGN = register("sea_foam_sign", () -> sign(SEA_FOAM_PLANKS.get(), MysticWoodTypes.SEA_FOAM));
        SEA_FOAM_WALL_SIGN = register("sea_foam_wall_sign", () -> wallSign(SEA_FOAM_SIGN.get(), MysticWoodTypes.SEA_FOAM));
        SEA_FOAM_HANGING_SIGN = register("sea_foam_hanging_sign", () -> hangingSign(SEA_FOAM_PLANKS.get(), MysticWoodTypes.SEA_FOAM));
        SEA_FOAM_WALL_HANGING_SIGN = register("sea_foam_wall_hanging_sign", () -> wallHangingSign(SEA_FOAM_HANGING_SIGN.get(), MysticWoodTypes.SEA_FOAM));

        /// tropics
        TROPICAL_LEAVES = register("tropical_leaves", () -> leaves(SoundType.GRASS));
        TROPICAL_SAPLING = register("tropical_sapling", () -> sapling(new MysticTreeGrowers(TreeFeatures.OAK)));///new MysticMegaTreeGrowers(MysticTreeFeatures.TROPICAL_TREE, MysticTreeFeatures.LARGE_TROPICAL_TREE)));
        TROPICAL_LOG = register("tropical_log", () -> log(MapColor.COLOR_BLUE, MapColor.COLOR_BROWN));
        STRIPPED_TROPICAL_LOG = register("stripped_tropical_log", () -> log(MapColor.COLOR_BLUE));
        TROPICAL_WOOD = register("tropical_wood", () -> log(MapColor.COLOR_BLUE, MapColor.COLOR_BROWN));
        STRIPPED_TROPICAL_WOOD = register("stripped_tropical_wood", () -> log(MapColor.COLOR_BLUE));
        TROPICAL_PLANKS = register("tropical_planks", () -> planks(MapColor.COLOR_BLUE));
        TROPICAL_STAIRS = register("tropical_stairs", () -> stairs(TROPICAL_PLANKS.get()));
        TROPICAL_SLAB = register("tropical_slab", () -> slab(TROPICAL_PLANKS.get()));
        TROPICAL_FENCE = register("tropical_fence", () -> fence(TROPICAL_PLANKS.get()));
        TROPICAL_FENCE_GATE = register("tropical_fence_gate", () -> fenceGate(TROPICAL_PLANKS.get(), MysticWoodTypes.TROPICAL));
        TROPICAL_BUTTON = register("tropical_button", () -> button(MysticBlockSetTypes.TROPICAL));
        TROPICAL_PRESSURE_PLATE = register("tropical_pressure_plate", () -> pressurePlate(TROPICAL_PLANKS.get(), MysticBlockSetTypes.TROPICAL));
        TROPICAL_TRAPDOOR = register("tropical_trapdoor", () -> trapdoor(TROPICAL_PLANKS.get(), MysticBlockSetTypes.TROPICAL));
        TROPICAL_DOOR = register("tropical_door", () -> door(TROPICAL_PLANKS.get(), MysticBlockSetTypes.TROPICAL));
        TROPICAL_SIGN = register("tropical_sign", () -> sign(TROPICAL_PLANKS.get(), MysticWoodTypes.TROPICAL));
        TROPICAL_WALL_SIGN = register("tropical_wall_sign", () -> wallSign(TROPICAL_SIGN.get(), MysticWoodTypes.TROPICAL));
        TROPICAL_HANGING_SIGN = register("tropical_hanging_sign", () -> hangingSign(TROPICAL_PLANKS.get(), MysticWoodTypes.TROPICAL));
        TROPICAL_WALL_HANGING_SIGN = register("tropical_wall_hanging_sign", () -> wallHangingSign(TROPICAL_HANGING_SIGN.get(), MysticWoodTypes.TROPICAL));

        VANILLA_LEAVES = register("vanilla_leaves", () -> leaves(SoundType.GRASS));
        VANILLA_SAPLING = register("vanilla_sapling", () -> sapling(new MysticTreeGrowers(TreeFeatures.OAK)));///MysticTreeFeatures.VANILLA_TREE)));
        VANILLA_LOG = register("vanilla_log", () -> log(MapColor.TERRACOTTA_WHITE, MapColor.TERRACOTTA_WHITE));
        STRIPPED_VANILLA_LOG = register("stripped_vanilla_log", () -> log(MapColor.TERRACOTTA_WHITE));
        VANILLA_WOOD = register("vanilla_wood", () -> log(MapColor.TERRACOTTA_WHITE, MapColor.COLOR_BROWN));
        STRIPPED_VANILLA_WOOD = register("stripped_vanilla_wood", () -> log(MapColor.TERRACOTTA_WHITE));
        VANILLA_PLANKS = register("vanilla_planks", () -> planks(MapColor.TERRACOTTA_WHITE));
        VANILLA_STAIRS = register("vanilla_stairs", () -> stairs(VANILLA_PLANKS.get()));
        VANILLA_SLAB = register("vanilla_slab", () -> slab(VANILLA_PLANKS.get()));
        VANILLA_FENCE = register("vanilla_fence", () -> fence(VANILLA_PLANKS.get()));
        VANILLA_FENCE_GATE = register("vanilla_fence_gate", () -> fenceGate(VANILLA_PLANKS.get(), MysticWoodTypes.VANILLA));
        VANILLA_BUTTON = register("vanilla_button", () -> button(MysticBlockSetTypes.VANILLA));
        VANILLA_PRESSURE_PLATE = register("vanilla_pressure_plate", () -> pressurePlate(VANILLA_PLANKS.get(), MysticBlockSetTypes.VANILLA));
        VANILLA_TRAPDOOR = register("vanilla_trapdoor", () -> trapdoor(VANILLA_PLANKS.get(), MysticBlockSetTypes.VANILLA));
        VANILLA_DOOR = register("vanilla_door", () -> door(VANILLA_PLANKS.get(), MysticBlockSetTypes.VANILLA));
        VANILLA_SIGN = register("vanilla_sign", () -> sign(VANILLA_PLANKS.get(), MysticWoodTypes.VANILLA));
        VANILLA_WALL_SIGN = register("vanilla_wall_sign", () -> wallSign(VANILLA_SIGN.get(), MysticWoodTypes.VANILLA));
        VANILLA_HANGING_SIGN = register("vanilla_hanging_sign", () -> hangingSign(VANILLA_PLANKS.get(), MysticWoodTypes.VANILLA));
        VANILLA_WALL_HANGING_SIGN = register("vanilla_wall_hanging_sign", () -> wallHangingSign(VANILLA_HANGING_SIGN.get(), MysticWoodTypes.VANILLA));

        /// potted plants
        ///POTTED_STRAWBERRY_SAPLING = register("potted_strawberry_sapling", () -> potted(POTTED_STRAWBERRY_SAPLING.get()));
        ///POTTED_STRAWBERRY_BUSH = register("potted_strawberry_bush", () -> potted(POTTED_STRAWBERRY_BUSH.get()));
        ///POTTED_PINK_DAISIES = register("potted_pink_daisies", () -> potted(POTTED_PINK_DAISIES.get()));
        ///POTTED_LAVENDER_SAPLING = register("potted_lavender_sapling", () -> potted(POTTED_LAVENDER_SAPLING.get()));
        ///POTTED_LAVENDER = register("potted_lavender", () -> potted(POTTED_LAVENDER.get()));
        ///POTTED_BUTTERFLY_BUSH = register("potted_butterfly_bush", () -> potted(POTTED_BUTTERFLY_BUSH.get()));
        ///POTTED_PINK_CHERRY_BLOSSOM_SAPLING = register("potted_pink_cherry_blossom_sapling", () -> potted(POTTED_PINK_CHERRY_BLOSSOM_SAPLING.get()));
        ///POTTED_WHITE_CHERRY_BLOSSOM_SAPLING = register("potted_white_cherry_blossom_sapling", () -> potted(POTTED_WHITE_CHERRY_BLOSSOM_SAPLING.get()));
        ///POTTED_SPRING_BAMBOO = register("potted_spring_bamboo", () -> potted(POTTED_SPRING_BAMBOO.get()));
        ///POTTED_STRIPPED_SPRING_BAMBOO = register("potted_stripped_spring_bamboo", () -> potted(POTTED_STRIPPED_SPRING_BAMBOO.get()));
        ///POTTED_PEONY_BUSH = register("potted_peony_bush", () -> potted(POTTED_PEONY_BUSH.get()));
        ///POTTED_MAPLE_SAPLING = register("potted_maple_sapling", () -> potted(POTTED_MAPLE_SAPLING.get()));
        ///POTTED_SPICED_MAPLE_SAPLING = register("potted_spiced_maple_sapling", () -> potted(POTTED_SPICED_MAPLE_SAPLING.get()));
        ///POTTED_ORANGE_MAPLE_SAPLING = register("potted_orange_maple_sapling", () -> potted(POTTED_ORANGE_MAPLE_SAPLING.get()));
        ///POTTED_YELLOW_MAPLE_SAPLING = register("potted_yellow_maple_sapling", () -> potted(POTTED_YELLOW_MAPLE_SAPLING.get()));
        ///POTTED_ASTER = register("potted_aster", () -> potted(POTTED_ASTER.get()));
        ///POTTED_GOLDENROD = register("potted_goldenrod", () -> potted(POTTED_GOLDENROD.get()));
        ///POTTED_PEACH_SAPLING = register("potted_peach_sapling", () -> potted(POTTED_PEACH_SAPLING.get()));
        ///POTTED_DESERT_SHRUB = register("potted_desert_shrub", () -> potted(POTTED_DESERT_SHRUB.get()));
        ///POTTED_DESERT_LILY = register("potted_desert_lily", () -> potted(POTTED_DESERT_LILY.get()));
        ///POTTED_WILDFLOWER = register("potted_wildflower", () -> potted(POTTED_WILDFLOWER.get()));
        ///POTTED_SAGUARO_CACTUS = register("potted_saguaro_cactus", () -> potted(POTTED_SAGUARO_CACTUS.get()));
        ///POTTED_PRICKLY_CACTUS = register("potted_prickly_cactus", () -> potted(POTTED_PRICKLY_CACTUS.get()));
        ///POTTED_SEA_SHRUB = register("potted_sea_shrub", () -> potted(POTTED_SEA_SHRUB.get()));
        ///POTTED_MILKWEED = register("potted_milkweed", () -> potted(POTTED_MILKWEED.get()));
        ///POTTED_SEA_THRIFT = register("potted_sea_thrift", () -> potted(POTTED_SEA_THRIFT.get()));
        ///POTTED_SEA_OATS = register("potted_sea_oats", () -> potted(POTTED_SEA_OATS.get()));
        ///POTTED_TROPICAL_SAPLING = register("potted_tropical_sapling", () -> potted(POTTED_TROPICAL_SAPLING.get()));
        ///POTTED_VANILLA_SAPLING = register("potted_vanilla_sapling", () -> potted(POTTED_VANILLA_SAPLING.get()));
        ///POTTED_JUNGLE_SHRUB = register("potted_jungle_shrub", () -> potted(POTTED_JUNGLE_SHRUB.get()));
        ///POTTED_HYDRANGEA_BUSH = register("potted_hydrangea_bush", () -> potted(POTTED_HYDRANGEA_BUSH.get()));
        ///POTTED_HIBISCUS = register("potted_hibiscus", () -> potted(POTTED_HIBISCUS.get()));
    }

    private static RegistryObject<Block> register(String name, Supplier<Block> block) {
        return REGISTRY.register(BuiltInRegistries.BLOCK, name, block);
    }

}